15.0 add xml ids moved from mail to base
legalsylvain/OpenUpgrade pull request #4
Opened 2022-05-10 16:45 UTC by jcdrubay

2022-05-10 19:46 UTC, legalsylvain commented
First commit is not desired i think. Otherwise. Lgtm. Thanks for the contribution !

2022-05-10 23:53 UTC, jcdrubay commented
Without the first commit, the upgrade cannot run... anyway, we can handle in 2 separate PRs.

I will go "all the way" with this PR including removing the obsolete function.
I will consider this PR as a migration PR.

I prefer that option, so I can continue pushing code with separate commits to handle whichever issue I may bump into.

Creating one PR for one fix will be very tedious + I am not sure if the fix is good until I can test when there will be no more issues...

I hope this works for you... later on, we can re-create one PR per issue if you prefer.

I am updating the PR summary.

2022-05-11 10:57 UTC, jcdrubay commented
@legalsylvain FYI, I got a first successful run for the upgrade my project which depends on very few native odoo modules today. 

Then, I will be:

- reviewing the analysis file of each module to check if I missed something.
- testing more

I will create dedicated PR for each module when I see fit. Should I continue submitting PR to your repo or should I switch to OCA repo?
I started with this one: https://github.com/OCA/OpenUpgrade/pull/3242

If you agree we could merge this PR? 
I could squash the commits if you want. Let me know.

Also, it would be great  if you could give me some inputs for the 2 non-blocking opened issues I have.
https://github.com/jcdrubay/OpenUpgrade/issues

2022-05-11 12:52 UTC, jcdrubay commented
I think that all that need to be done for base is done.

2022-05-11 16:24 UTC, legalsylvain requested changes
Thanks @jcdrubay for your work ! 

> Creating one PR for one fix will be very tedious + I am not sure if the fix is good until I can test when there will be no more issues...

:100: 

Indeed. This PR is the perfect way to move one.

> I think that all that need to be done for base is done.

Nice news ! 

Review : 
- code review, LGTM.
- Test review : it is failing. Reason : ``test.yml`` is outdated.  the test try to restore a V13 database, and then realize the migration script 14->15. Quite normal it is failing ;-) could you change that file ? https://github.com/legalsylvain/OpenUpgrade/blob/15.0-mig-openupgrade_framework/.github/workflows/test.yml#L47
(some 13 should be renamed in 14 and some 14 in 15...)

2022-05-11 16:24 UTC, legalsylvain commented on openupgrade_framework/odoo_patch/odoo/addons/base/models/ir_ui_view.py
> -    )
naive question : there is no blocking error if views are broken ?

2022-05-11 16:24 UTC, legalsylvain commented on openupgrade_scripts/scripts/base/15.0.1.3/pre-migration.py
> +            ("l10n_ec.state_ec_1", "base.state_ec_01"),
nitpicking (non blocking) : usually, in Openupgrade, we define a variable at the top of the file, and then just call ``rename_xml_ids`` in the main function. It is so more readable to see all the steps of the main file.

see for exemple : https://github.com/OCA/OpenUpgrade/blob/14.0/openupgrade_scripts/scripts/base/14.0.1.3/pre-migrate.py#L23

2022-05-12 23:18 UTC, jcdrubay commented
@legalsylvain Is it ok now?

- [1] in the .github/workflows/test.yml: I updated versions (not 100% sure if it's right)
- [2] I used a variable rename_xmlids which is then called by the migrate function
- [3] I answered your question related to the _postprocess_view function and removal of the validate argument

😄  🤞

2022-05-13 09:50 UTC, legalsylvain commented
Test are green ! Nice. Dôme bug in precommit install. Otherwise. Lgtm !

2022-05-13 10:34 UTC, etobella commented
@legalsylvain I think https://github.com/jcdrubay/OpenUpgrade/pull/5 can solve the pre-commit issue

2022-05-13 12:09 UTC, legalsylvain commented
/ocabot merge nobump

2022-05-13 12:11 UTC, etobella commented
I thin ocabot will not work on your repo :thinking:

2022-05-13 12:31 UTC, legalsylvain commented
Let's try again ?

/ocabot merge nobump

2022-05-13 12:41 UTC, legalsylvain commented
weird

2022-05-13 12:41 UTC, merged